CREATE TABLE IF NOT EXISTS Pedido(
	PK_ID INT AUTO_INCREMENT,
	FK_UsuarioID INT,

	PRIMARY KEY (PK_ID),
	
	CONSTRAINT FK_UsuarioID
	FOREIGN KEY (FK_UsuarioID)
	REFERENCES Usuario(PK_ID)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Pedido_Producto(
	FK_PedidoID INT,
	FK_ProductoID INT,
	Cantidad INT DEFAULT 1,

	PRIMARY KEY (FK_PedidoID, FK_ProductoID),

	CONSTRAINT FK_ProductoID
	FOREIGN KEY (FK_ProductoID)
	REFERENCES Producto(PK_ID)
	ON DELETE CASCADE,

	CONSTRAINT FK_PedidoID
	FOREIGN KEY (FK_PedidoID)
	REFERENCES Pedido(PK_ID)
	ON DELETE CASCADE
);
